# Generated by Django 6.0 on 2025-12-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_for_sale',
            field=models.BooleanField(default=False),
        ),
    ]
