# Generated by Django 6.0 on 2025-12-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cartitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_model',
            field=models.CharField(choices=[('card', 'Card'), ('money', 'Money')], default=('money', 'Money'), max_length=30),
        ),
    ]
