# Generated by Django 6.0 on 2026-01-01 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_payment_model'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
